### ISSUE TITLE
Kraken-api-java returns Invalid key

### ISSUE THREAD

**Issue by jitendraauxesis** [nyg/kraken-api-java#1]
I tried this nyg/kraken-api-java to make api call with Krakan Add Order Api but I got  
{"error":["EAPI:Invalid key"]}.
To obtain signature I've seen the hashmacsha512 as 7TfGipZ/gPTk4/P6eV2P6eQCjN9UhTlnXM6vcfdeYbVYPtVGz+BYzpd5jNnc35xkwtQMWxvNhvljqH97U8XBYw==
Is this correct or else any other issue is there?

**Comment by nyg** [comment]
Hello, sorry for the late answer :).

I tried with my API keys and it worked properly, maybe it was an issue with you API key permissions?

I used the following code:

```java
input.clear();
input.put("ordertype", "limit");
input.put("type", "sell");
input.put("volume", "1");
input.put("pair", "XLTCZUSD");
input.put("price", "1000");
input.put("oflags", "post,fciq");
input.put("validate", "false");
response = api.queryPrivate(Method.ADD_ORDER, input);
System.out.println(response);
```
